name: Publish

on:
  push:
    tags: [ 'v0.[0-9]+.[0-9]+' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Tests
        run: |
          pnpm run lint
          pnpm run test

      - name: Publish to NPM
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Version already published
        if: steps.publish.outputs.type == 'none'
        run: |
          echo "Version ${{ steps.publish.outputs.old-version }} already exists."

      - name: New version published
        if: steps.publish.outputs.type != 'none'
        run: |
          echo "New ${{ steps.publish.outputs.type }} version ${{ steps.publish.outputs.version }} published. Was ${{ steps.publish.outputs.old-version }}."
